/** @jest-environment jsdom */
import React from 'react';
import { screen, render, fireEvent, waitFor } from '@testing-library/react';
import AssistImage from '../AssistImage';
import { beforeEach, describe, expect, it, jest } from '@jest/globals';
import {Element} from "react-scroll";

const mockOpenAiApi = jest.fn();
jest.mock('../../api/openAiApi', () => {
	return {
		__esModule: true,
		default: () => mockOpenAiApi
	}
});

// Mock react-scroll
const mockScrollTo = jest.fn();
jest.mock('react-scroll', () => ({
	scroller: {
		scrollTo: () => mockScrollTo
	}
}));

describe('AssistImage Component Tests', () => {
	beforeEach(() => {
	});

	it.only('renders the component without errors', () => {
		const {getAllByText} = render(<AssistImage prompt={"test"}/>);

		// Check if the "Generate Image" button is present
		const button = getByText(/Generate Image/i);
		expect(button).toBeDefined();
	});

	it('calls the GenerateImage API and displays the image when the button is clicked', async () => {
		const mockImageData = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII='; // Example base64 image data
		const mockImageResponse = { data: mockImageData };
		const { GenerateImage } = require('../../api/openAiApi');
		// Use the spy to control the mock's behavior
		GenerateImage.mockResolvedValue(mockImageResponse);
		
		render(<AssistImage prompt="test" />);
		fireEvent.click(screen.getByRole('button', { name: /Generate Image/i }));

		// Check if the spinner is displayed while waiting for the API response
		expect(screen.getByRole('status')).toBeVisible();

		await waitFor(() => {
			// Check if the image is displayed with the correct source
			const image = screen.getByRole('img', { name: /Generated by OpenAI/i });
			expect(image).toBeInTheDocument();
			expect(image).toHaveAttribute('src', mockImageData);
		});

		// Check if the spinner is hidden after the image loads
		expect(screen.queryByRole('status')).not.toBeInTheDocument();
	});

	it('handles API errors gracefully', async () => {
		const { GenerateImage } = require('../../api/openAiApi');
		// Use the spy to control the mock's behavior
		GenerateImage.mockRejectedValue(new Error('API Error'));

		render(<AssistImage prompt="test" />);
		fireEvent.click(screen.getByRole('button', { name: /Generate Image/i }));

		// Check if the spinner is eventually hidden, even on error.
		await waitFor(() =>
			expect(screen.queryByRole('status')).not.toBeInTheDocument()
		);

		// Add assertions to check for error handling behavior, e.g., an error message
		// expect(screen.getByText(/Error generating image/i)).toBeVisible();  //  Requires displaying an error in the component
	});

	it('updates image size', async () => {
		render(<AssistImage prompt="test" />);
		const newSize = '500';
		fireEvent.change(screen.getByPlaceholderText('350'), {
			target: { value: newSize },
		});
		expect(screen.getByPlaceholderText('350').value).toEqual(newSize);

		// Verify that this size gets used -  mock the api call as above, and check the width prop.
	});


	// Add more tests for other functionalities like:
	// - Clearing the image
	// - Handling different image sizes
	// - Edge cases (empty prompt, invalid prompt, etc.)
});