import React, {useState} from "react";
import {Element, scroller} from "react-scroll";
import Image from "react-bootstrap/Image";
import Spinner from "react-bootstrap/Spinner";
import Button from "react-bootstrap/Button";
import Alert from "react-bootstrap/Alert";
import GenerateImage from "../api/openAiApi";
import Form from "react-bootstrap/Form";
/*
import FormControl from "react-bootstrap/FormControl";
import FormLabel from "react-bootstrap/FormLabel";
*/

const AssistImage = () => {
  const [imageUrl, setImageUrl] = useState(null);
  const [imageSize, setImageSize] = useState(350);
  const [spinner, setSpinner] = useState(false);

  const scrollToImage = () => {
    scroller.scrollTo('ImageUrl', {
      duration: 500, delay: 0, smooth: 'easeInOutQuart'
    });
  };

  const handleImageSize = (event) => {
    const size = event.target.value;
    setImageSize(size);
  }

  const getImageUrl = async () => {
    setSpinner(true);
    const imageUrl = await GenerateImage(question);
    console.log('image url:', imageUrl);
    if (imageUrl) {
      await setImageUrl(imageUrl);
      scrollToImage();
      /*
            setCode('');
      */
    }
    setSpinner(false);
  }

  function clearImage() {
    setImageUrl(null);
  }

  return (
    <React.Fragment>
      <Form>
        {imageUrl && (
          <Alert className={'m-2'}>
            {imageUrl}
          </Alert>)
        }
        <Element id={'ImageUrl'}>
          {imageUrl &&
            <Image src={imageUrl || ''}
                   alt="Generated by OpenAI"
                   width={imageSize}
                   className={'my-24'}
            />}
        </Element>
        <Form.Label title={'ImageSize'} htmlFor={'ImageSize'} column={0}>Image Size:
          <Form.Control
            onChange={handleImageSize}
            style={{width: '75px', marginLeft: '15px'}}
            type="number"
            as={'input'}
            id="number-input"
            placeholder="350"
          />
        </Form.Label>
        <Button id={'imageUrl'}
                className={'mr-2'}
                variant='secondary'
                onClick={async (e) => {
                  await getImageUrl(e)
                  await scrollToImage();
                }}
        >
          Generate Image
        </Button>
      </Form>
      <Spinner animation="border" role="status" hidden={!spinner}/>
    </React.Fragment>
  )
}

export default AssistImage;